syriac_letters = [
    ("ܐ", "Alap"),
    ("ܒ", "Beth"),
    ("ܓ", "Gamal"),
    ("ܕ", "Dalath"),
    ("ܗ", "Heh"),
    ("ܘ", "Waw"),
    ("ܙ", "Zayn"),
    ("ܚ", "Heth"),
    ("ܛ", "Teth"),
    ("ܝ", "Yodh"),
    ("ܟ", "Kap"),
    ("ܠ", "Lamadh"),
    ("ܡ", "Mym"),
    ("ܢ", "Nun"),
    ("ܣ", "Simkath"),
    ("ܥ", "'e"),
    ("ܦ", "Pe"),
    ("ܨ", "Sade"),
    ("ܩ", "Qop"),
    ("ܪ", "Resh"),
    ("ܫ", "Shyn"),
    ("ܬ", "Taw")
]